//This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const signle: string;
export const codes: string;
export const codesTab: string;
export const codesSection: string;
export const result: string;
