//This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const single: string;
export const collect: string;
export const collectMobile: string;
export const codes: string;
export const codesTab: string;
export const otherTab: string;
export const activeTab: string;
export const codesSection: string;
export const otherSection: string;
export const activeSection: string;
export const result: string;
export const mobileResult: string;
export const loading: string;
export const spin: string;
export const mobile: string;
export const loaded: string;
export const error: string;
export const errorTitle: string;
export const errorTip: string;
