import Clock from '../clock';
import Axes from '../axes';
import Cutout from '../cutout';
import Shape from '../shape';
import Editor from '../editor';
import Zoom from '../zoom';
import Collide01 from '../collide_01';
import Collide02 from '../collide_02';
import Collide03 from '../collide_03';
import Animate from '../animate';

new Shape().render();
new Clock().render();
new Axes().render();
new Cutout().render();
new Editor().render();
new Zoom().render();
new Collide01().render();
new Collide02().render();
new Collide03().render();
let time = new Animate();
time.render().then(() => time.createButton());
